### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/PlanBot#1]
It runs on the server but does nothing, and I'm pretty sure it's supposed to have done something since both @amazansky and I have assigned issues for longer than a week. I've tried running it manually and it just doesn't log anything, although I'm not sure it's supposed to log anything.

Redacted config:
```toml
[github]
organization = "MyHomeworkSpace"
repos = ["client", "api-server"]
privateKey = "./privatekey.pem"
appId = 12345 # redacted
installationId = 12345 # redacted
ignoreLabels = ["waiting for details"]

[unassign]
daysUntilWarning = 5
daysUntilUnassign = 7

[slack]
token = "redacted"
errlogChannel = "redacted"

[users]
willbarkoff = "redacted"
thatoddmailbox = "redacted"
amazansky = "redacted"
```
